name: Bug report
description: Report a reproducible problem in Ailert.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please include enough detail for someone else to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide numbered steps.
      placeholder: |
        1. Open Ailert
        2. Tap ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: input
    id: ios_version
    attributes:
      label: iOS version
      placeholder: iOS 18.2
    validations:
      required: true
  - type: input
    id: device_model
    attributes:
      label: Device model
      placeholder: iPhone 15 Pro
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Add relevant logs/screenshots. Redact sensitive information first.
